# Generated by Django 3.2.23 on 2024-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_accounts',
            name='parent_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chart_of_accounts',
            name='sub_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
