# Generated by Django 3.2.23 on 2024-01-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0009_paymenttermsupdates'),
        ('Company_Staff', '0005_auto_20240124_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnk_name', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bnk_branch', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bnk_acno', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bnk_ifsc', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bnk_bal_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Debit', max_length=220)),
                ('bnk_opnbal', models.FloatField(blank=True, null=True)),
                ('bnk_bal', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='bank/')),
                ('status', models.TextField(default='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_cur_amount', models.FloatField(blank=True, null=True)),
                ('trans_amount', models.FloatField(blank=True, null=True)),
                ('trans_adj_amount', models.FloatField(blank=True, null=True)),
                ('trans_adj_date', models.DateField(blank=True, null=True)),
                ('trans_type', models.CharField(choices=[('Opening Balance', 'Opening Balance'), ('Bank to Bank', 'Bank to Bank'), ('Bank to Cash', 'Bank to Cash'), ('Cash to Bank', 'Cash to Bank'), ('Bank Adjustment', 'Bank Adjustment')], max_length=220)),
                ('trans_adj_type', models.CharField(choices=[('', ''), ('Balance Increase', 'Balance Increase'), ('Balance Decrease', 'Balance Decrease')], max_length=220)),
                ('trans_desc', models.CharField(blank=True, max_length=220, null=True)),
                ('bank_to_bank_no', models.PositiveIntegerField(blank=True, null=True)),
                ('banking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.banking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hist_cur_amount', models.FloatField(blank=True, null=True)),
                ('hist_amount', models.FloatField(blank=True, null=True)),
                ('hist_adj_amount', models.FloatField(blank=True, null=True)),
                ('hist_adj_date', models.DateField(auto_now_add=True, null=True)),
                ('hist_action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=220)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='BankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hist_adj_amount', models.FloatField(blank=True, null=True)),
                ('hist_adj_date', models.DateField(auto_now_add=True, null=True)),
                ('hist_action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=220)),
                ('banking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.banking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
