# Generated by Django 5.0.1 on 2024-02-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0008_companyrepeatevery'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrepeatevery',
            name='repeat_every',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
