# Generated by Django 5.0.1 on 2024-02-02 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0009_companyrepeatevery_repeat_every'),
        ('Register_Login', '0015_remove_paymenttermsupdates_interested_to_continue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(blank=True, max_length=220, null=True)),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('first_name', models.CharField(blank=True, max_length=220, null=True)),
                ('last_name', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_display_name', models.CharField(blank=True, max_length=220, null=True)),
                ('company_name', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_email', models.EmailField(max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=220, null=True)),
                ('skype', models.CharField(blank=True, max_length=220, null=True)),
                ('designation', models.CharField(blank=True, max_length=220, null=True)),
                ('department', models.CharField(blank=True, max_length=220, null=True)),
                ('website', models.CharField(blank=True, max_length=220, null=True)),
                ('GST_treatement', models.CharField(blank=True, max_length=220, null=True)),
                ('GST_number', models.CharField(blank=True, max_length=220, null=True)),
                ('PAN_number', models.CharField(blank=True, max_length=220, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=220, null=True)),
                ('tax_preference', models.CharField(blank=True, max_length=220, null=True)),
                ('currency', models.CharField(blank=True, max_length=220, null=True)),
                ('opening_balance_type', models.CharField(blank=True, max_length=220, null=True)),
                ('opening_balance', models.FloatField(blank=True, null=True)),
                ('credit_limit', models.FloatField(blank=True, null=True)),
                ('price_list', models.CharField(blank=True, max_length=220, null=True)),
                ('portal_language', models.CharField(blank=True, max_length=220, null=True)),
                ('facebook', models.CharField(blank=True, max_length=220, null=True)),
                ('twitter', models.CharField(blank=True, max_length=220, null=True)),
                ('current_balance', models.FloatField(blank=True, null=True)),
                ('billing_attention', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_pincode', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_mobile', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_fax', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_attention', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_pincode', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_mobile', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_fax', models.CharField(blank=True, max_length=220, null=True)),
                ('remarks', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_status', models.CharField(blank=True, max_length=220, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('company_payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.company_payment_term')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContactPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('first_name', models.CharField(blank=True, max_length=220, null=True)),
                ('last_name', models.CharField(blank=True, max_length=220, null=True)),
                ('email', models.EmailField(blank=True, max_length=220, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=220, null=True)),
                ('mobile', models.CharField(blank=True, max_length=220, null=True)),
                ('skype', models.CharField(blank=True, max_length=220, null=True)),
                ('designation', models.CharField(blank=True, max_length=220, null=True)),
                ('department', models.CharField(blank=True, max_length=220, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=220, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
