# Generated by Django 4.1.7 on 2024-03-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0011_godown_godownhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown',
            name='Action',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='godown',
            name='status',
            field=models.CharField(default='Active', max_length=200, null=True),
        ),
    ]
