# Generated by Django 4.1.7 on 2024-03-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0015_remove_paymenttermsupdates_interested_to_continue'),
        ('Company_Staff', '0012_godown_action_godown_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='godown',
            old_name='Action',
            new_name='action',
        ),
        migrations.CreateModel(
            name='GodownComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.godown')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
