# Generated by Django 4.1.7 on 2024-03-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0013_rename_action_godown_action_godowncomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
